
package com.tutorialspedia.jaxwsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWS", targetNamespace = "http://tutorialspedia.com/UserWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWS {


    /**
     * 
     * @param addRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddUser", action = "http://tutorialspedia.com/UserWS/AddUser")
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "AddUser", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.AddUser")
    @ResponseWrapper(localName = "AddUserResponse", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.AddUserResponse")
    public String addUser(
        @WebParam(name = "AddRequest", targetNamespace = "")
        UserType addRequest);

    /**
     * 
     * @param userID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteUser", action = "http://tutorialspedia.com/UserWS/DeleteUser")
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.DeleteUserResponse")
    public String deleteUser(
        @WebParam(name = "UserID", targetNamespace = "")
        int userID);

    /**
     * 
     * @param updateUserRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateUser", action = "http://tutorialspedia.com/UserWS/UpdateUser")
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "UpdateUser", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.UpdateUser")
    @ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.UpdateUserResponse")
    public String updateUser(
        @WebParam(name = "UpdateUserRequest", targetNamespace = "")
        UserType updateUserRequest);

    /**
     * 
     * @param userName
     * @return
     *     returns com.tutorialspedia.jaxwsservice.UserType
     */
    @WebMethod(operationName = "GetUser", action = "http://tutorialspedia.com/UserWS/GetUser")
    @WebResult(name = "GetUsersResponse", targetNamespace = "")
    @RequestWrapper(localName = "GetUser", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.GetUser")
    @ResponseWrapper(localName = "GetUserResponse", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.GetUserResponse")
    public UserType getUser(
        @WebParam(name = "UserName", targetNamespace = "")
        String userName);

    /**
     * 
     * @return
     *     returns com.tutorialspedia.jaxwsservice.UsersType
     */
    @WebMethod(operationName = "GetAllUsers", action = "http://tutorialspedia.com/UserWS/GetAllUser")
    @WebResult(name = "GetUsersResponse", targetNamespace = "")
    @RequestWrapper(localName = "GetAllUsers", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.GetAllUsers")
    @ResponseWrapper(localName = "GetAllUsersResponse", targetNamespace = "http://tutorialspedia.com/UserWS/", className = "com.tutorialspedia.jaxwsservice.GetAllUsersResponse")
    public UsersType getAllUsers();

}
